### ISSUE TITLE
LinksToFragment: system for file uploading and scanning

### ISSUE THREAD

**Issue by andreasdieryck** [GhostWording/gw-config-apis#15]
@rhwy has recently created issues regarding a new way of
- interpolating files into other files
- calling for a random file based on a keyword system ("tags")

We can all view these here:
- https://github.com/GhostWording/gw-config-apis/issues/10
- https://github.com/GhostWording/gw-config-apis/issues/11
- https://github.com/GhostWording/gw-config-apis/issues/12

We would like to find the best system to:
1. Call for a file using its sequence ID
2. Retrieve this file among the others, quickly

And do the same with tags:
1. Calling for tags
2. Finding all the relevant files with right tags
3. Return one of these files 

@Frederikos Could you suggest a system that would allow us to do that, with as much flexibility as possible?
Thanks

**Comment by Frederikos** [comment]
we can add sequence id in master file
as for tags we can add them to groupname or to sequence file in masterfile
something like this. and i can understand if i need to donwload this sequence or user already answer it.
{
  "GroupName": "Visible-All",
  "SequenceFiles": [
    { "order" : 10, "file":"/data/bot/sequences/personality/ppEnergeticAfter.json.json"
"Tags":"jokes, fun",
"Id" : "ppEnergeticAfter"
},
  ]
}

**Comment by rhwy** [comment]
our idea with Olivier is that the fragments file has to be simple as possible because it's just a list for fragments where to pickup things. 

in that case we don't need order (because they are not intended to be executed sequentially.

Also, the id & tags are properties of the sequences not a specific thing of that fragments master file.

the only thing to do is to load and keep in memory these fragments. when call for an id or a specific you just have to do a lookup in memory.

**Comment by andreasdieryck** [comment]
After discussing with @OlivierBourdin and @Frederikos, we would like to suggest having the following system for the moment:

1. We use the properties in the sequences as it was defined by @rhwy in #11, 
That means, we should call a sequence id, as follows:
```
{
    "Type": "Node",
    "Id": "WouldYouLikeToFeelZen",
    
    "LinksToFragment": {
         "FragmentPath":"idOfMySequence"
    }
}
```

2. As previously defined, we put the fragments into a specific file for validation and we detail their sequence id

To make the client's life a bit easier, it will be quite convenient to at least have the sequence id in the Masterfile. This way, the client won't have to load and open all the files to identify which one it needs to display.

In this case, the master file could look something like this: 
```

[
	{"/bot/sequences/surveyquestions/AreYouHappy.json": "AreYouHappy"},
	{"/bot/sequences/surveyquestions/LiveInAnotherCountry.json":"LiveInAnotherCountry"},
	{"/bot/sequences/surveyquestions/GunsAllowedOrForbidden.json": "GunsAllowedOrForbidden"},
	{"/bot/sequences/surveyquestions/AreTheUNUsefulYesNo.json": "AreTheUNUsefulYesNo"},
	{"/bot/sequences/surveyquestions/YourCountryGoodExampleYesNo.json": "YourCountryGoodExampleYesNo"},      
	{"/bot/sequences/surveyquestions/GlobalWarming.json": "GlobalWarming"},
	{"/bot/sequences/surveyquestions/CheeseOrDessert.json": "CheeseOrDessert"}
]
```

What do you think about it? @Frederikos @rhwy is that a good compromise for the time being?

**Comment by rhwy** [comment]
ok for adding the id for me (it's tied to file, so it's not something subject to change like any other properties of the files)
but the format is not good. you wrote an array of objects with only one property which name is the name of file, which is not good. Iif we want to keep things simple, we could create a dictionary instead of an array and use the id as a key like that:

```
{
	"AreYouHappy"            : "/bot/sequences/surveyquestions/AreYouHappy.json",
	"LiveInAnotherCountry"   : "/bot/sequences/surveyquestions/LiveInAnotherCountry.json",
	"GunsAllowedOrForbidden" : "/bot/sequences/surveyquestions/GunsAllowedOrForbidden.json",
}
```

if @Frederikos agrees with me, it allows us to keep things simples but well formatted

**Comment by andreasdieryck** [comment]
Spot on: that's better.
