### ISSUE TITLE
[bot] define default behaviour and text for `Skip`

### ISSUE THREAD

**Issue by rhwy** [GhostWording/gw-config-apis#5]
we would like to have skippable sequence elements by adding the property `Skippable=true`.

With this activated, it's on the client responsibility to show a skip button, with the right text and button labels. what are: 
- the question text ? ("would you like to skip?" ...)
- the button labels ?
- the behaviour ? (when to show:  before showing commands? by adding a button `Skip` with the other options, etc ...)

**Comment by andreasdieryck** [comment]
So far, I always assumed that the default behaviour would be:

When `"Skippable": true,` is present, client should:
1. Display a `Skip` button, next to the other commands
2. Display this button to the far-right of the others, regardless of the presence or absence of the `"Randomize": true,` pair.

I can't really envision the presence of a question text anywhere here. It's an exit option, we want to keep it as invisible as possible.

If we really to ask "Do you wish to continue?" or "Would you like like to skip?", we can use the `"ContinueConfirmation"` along with the `"Type": "Pause"`. But again, I don't see a big use case for that.

What do you think?

**Comment by rhwy** [comment]
yep, it doesn't make sense now with the things we have in steps. 

showing a "skip button" on the right is the best option for now. In all the cases, user has to get some context (question+options), so the shortest solution is the skip button shown along the question+options.

We still have to:
- define the labels for the button
- agree that skip action, is stopping the execution of the current sequence and going directly to the next

**Comment by andreasdieryck** [comment]
@rhwy I agree with you. Now, on to the two points you are raising:

### 1. Defining the labels for the Skip button

What I suggest is the following:
- we should have default values that are set as follows: 
=> English: "Skip"
=> French: "Passer"
=> Spanish: "Passar"
- to call for the default values to be shown to the user, we should just input  `"Skippable": default,`
- that should cover 70 to 90% of cases

Now I guess there will cases where we will want to redefine Skip and give it another label. Example: "No opinion", "Not interested", "I don't care", "Next", "Give me a break", "Stop", "I don't give a damn", "Not my business", "I don't want to answer", "Out", etc...
Those are more or less all synonyms, but they can be expressed in very different contexts and their dissimilarities are very important

Therefore, I suggest that we can redefine quickly the Label of the `"Skip"` button by inputting the following

```
                  "Skippable": {
                        "en": "I don't care"
                         "fr": "Je m'en fous"
                   },
```

What do you think about this? I think it gives us a solid default use case, whilst we retain the flexibility to change it whenever necessary.


### 2. Defining the Skip behaviour

I agree with you. Whenever a user chooses to `"Skip"`, the sequence should end here and we should start the next one. This has a couple of implication:
- Skip will not be used in Stories. For instance if we want to tell the story of a murder crime and we want to have the public's opinion on who they think is the killer, they won't be able to skip the sequence, otherwise it will just be pointless
- We can have several skip on different elements of a sequence and they won't interact with one another
- `"Skip"` should not be used for sequences to which we want to have an end (when we need data from a user, for instance)

What do you guys think about this?

**Comment by andreasdieryck** [comment]
As suggested by @OlivierBourdin in our last conversation, we would like to make the Skip behaviour a default one. 

### 1. Default label

For the moment, the default label will be:
=> English: "Skip"
=> French: "Passer"
=> Spanish: "Pasar"

We will make tests and adjust to see which works best. 

By default, "Skip" should also appear at the far right of all of the other commands

### 2. Behaviour

When I click on Skip, i am redirected to the next sequence in the Masterfile.

### 3. When we don't want Skip to appear

There will be cases when:
- we want to force the user to answer
- Skip will be sort of irrelevant (or susbstituted by a "no")
- Skip will be sort of useless. Example: through the Stories

For these cases, we will want to use a property that would cancel the appearance of Skip by default.
Example: `"NotSkippable": "true"`


What do you think about it?

**Comment by OlivierBourdin** [comment]
Looks good too me, thanks !
We can also add that a Skip icon can be used instead of 'Skip' when available (ios and android)

**Comment by andreasdieryck** [comment]
Having discussed the above with @rhwy, we have reached the conclusion that we could have following principles in place:

### 1. Skip is a default button

By default, the users will always see a Skip button. The labels or visual used for this Skip will independently be decided and subject to experiments.

Hence, by default, ALL sequences (Huggy, Surveys, Stories, etc) will see a Skip button be added on the right of all the other commands.

### 2. We can override the content of the Skip button and change it to something else

As we said, the Skip button will contain a default label. This label can however be overridden using the following Properties:
```
{
   "Skippable": {
	  "value": true,
      "Label": {
		"en":"Not interested",
	        "fr": "Pas intéressé"
	  }
   }
}
``` 

This way, we can rewrite the Skip button as we want.

### 3. We can cancel the Skip button and force the user to use the other buttons

To do so, we would only need to write:
```
{
   "Skippable": {
	  "value":false
   }
}
```
 
@rhwy @OlivierBourdin Suggestions?

**Comment by OlivierBourdin** [comment]
Je vote pour

**Comment by rhwy** [comment]
👍

**Comment by AgnesGsd** [comment]
Je vote pour aussi !

**Comment by andreasdieryck** [comment]
Let's close it: my last addition shall now be engraved in stone
