### ISSUE TITLE
[bot] Sequence conditional entry

### ISSUE THREAD

**Issue by andreasdieryck** [GhostWording/gw-config-apis#8]
At the moment, when we parse a json sequence file, it is supposed to be shown to all users, unconditionally.

We would like to come up with a system that imposes conditions on whether a file is shown to a user. These conditions would be linked to the user's properties. Example: age, gender relationship status, marital status, children, number of children, music tastes, etc.. 

We would reuse these properties to show some sequences to some users and not others. 
Examples:
1. We want to send Iggy Pop's last album to people of more than 60 y.o AND who like jazz OR pop-rocl
2. We want to ask the marital status of people who are in couple and more than 50

Two things here:
- we think such a condition should be included as a Step, so that (i) we keep a uniform format without and (ii) can include it at any element of a sequence
- it will have new values and properties basically replicating an IF statement, so that the client can easily translate it

Here's what @Frederikos and I came up with:

```
{
   "Type": "Node",
   "Id": "MarriedYet",
   "Steps": [
      {
         "Type": "Condition",
         "Trigger": "EnterSequence",
         "Rule": "AllConditionsPassed",
         "Conditions": [
            {
               "Type": "Equals",
               "property": "ppSingle",
               "value": "false"
            },
            {
               "Type": "More",
               "property": "ppAge",
               "value": "50"
            }
         ]
      },
```

You can find the full sequence here: https://github.com/GhostWording/gw-config-apis/blob/master/data/bot/sequences/experiments/ppMarriedV3-A.json

In details:
- the `"Type"` would always be a `"Condition"`
- the `"Trigger"` would either be `"EnterSequence"` or `"NextSequence"`
- there would two "Rules": (i) `"AllConditionsPassed"` ; (ii) `"OneConditionPassed"` (AND/OR)
- the `"Conditions"` would include a `"Type"` (`Equals`/`More`/`Less`) and the properties and values we want

@rhwy, @Frederikos, @OlivierBourdin What do you think about it?

**Comment by rhwy** [comment]
Sounds good for me:
1. the format is verbose but avoid the hard work of parsing an expression (ie: condition="ppSingle==false && ppAge > 50")
2. the condition should be at the sequence level and not within a step (this means that when we’ll choose the next sequence to see within the sequence if there is a step of type condition and evaluate it with is not logical and too specific from the generic way of work of the steps) BUT on the other hand we already have the logic of reading the steps so it will be easier to implement (than creating a new property of Condition) -> I'm not sure yet about the best option

**Comment by andreasdieryck** [comment]
1. Yeah, we tried something else first such as a classic IF statement, but as @Frederikos pointed out, we need it to be in JSON format anyway, otherwise we wouldn't be able to parse
2. Let's keep it simple for the moment. I suggest we make it only possible to have it at the sequence level (i.e. in first position of the first step)

For future discussions however, we should consider:
A. The possibility to make part of the sequences conditional. I.e. As a user, I can see the first part of the sequence, but not the last part because of my user properties
B. The possibility to make bits of sequences conditional. I.e. As a user, there will be bits of a sequence I will see and other bits I won't see, depending on my user properties. Example: if I am in couple, a Story about love would open a question on my relationship and I will see love Gifs. Whilst if ppSingle is true, I will see something else related to my relationship status.

Let's come back to that when it will be relevant.
Does it sound good to you @rhwy ?

**Comment by OlivierBourdin** [comment]
Conditions say if we should enter a sequence or not.
They could be expressed in the master files, or as a property of the sequences.
I don't like the idea of having them expressed inside the steps. It does not look like such a great hack to me.

**Comment by OlivierBourdin** [comment]
Also I prefer expressions to be expressed as standard expressions
Like in (ppHasShoes && ppLikesSports) || ppLikesRunning
Parsing an expression is not that difficult. In my previous company, we used to ask software engineers to do this as a test before hiring them.
Worst of case, helpful librairies can be found
https://tomassetti.me/parsing-in-java/

**Comment by andreasdieryck** [comment]
@OlivierBourdin 

1. It could be expressed in the master file: I think we would lose a lot of visibility by doing that and the Master file would be an endless collection of conditions. Plus, it means we wouldn't have the option to extend this principle to parts of sequences in the future (example: long stories, what if we want to make some content dependent on a user property, such as the previous stories he/she has read or media preferences?)
2. It could be expressed as a property in a sequence. I agree with that, a lot. Here's an option (to continue on our last example):

```
	{
	"Trigger": {
		"Rule": "AllConditionsPassed",
		"Conditions": [
			{
				"Type": "Equals",
				"property": "ppSingle",
				"value": "false"
			},
			{
				"Type": "More",
				"property": "ppAge",
				"value": "50"
			}
		]
	},
	"Type": "Node",
	"Id": "MarriedYet",
	"Steps": [
		{
			"Type": "Text",
			"Label": {
				"en": "Are you married yet?"
			}
		}
	],
        ...
```
We could even start adding it as a property of other steps of sequence (long-term).
What do you think about it @rhwy @OlivierBourdin ?

**Comment by OlivierBourdin** [comment]
We can put "Condition" = "xxxxx" as a property of the Sequence (and could also choose to add some later on in the master files, because sequences may not always know which conditions are relevant, because they lack context)
To begin with, we can limit complexity of a condition. We can start with 
a/ a single variable name, such as "Condition" = "ppSingle"
later on, when we have awesome ;) ;) ;) programming skills, move on to 
b/ a single operator, "&&" , such as "Condition" = "ppSingle && ppOverTwenty"
That should be good enough to begin with, and hopefully ;););) simple enough to implement

**Comment by andreasdieryck** [comment]
@OlivierBourdin 
Ok - but specifying "Condition" = "ppSingle" doesn't lead us anywhere.  "ppSingle " is a property, we need to know its value to actually make something out of it. At the very least, we need to specify both properties and values.

It could look like this:

```
	{
		"Condition": 
			{
				"property": "ppSingle",
				"value": "false"
			}
	},
	"Type": "Node",
	"Id": "MarriedYet",
	"Steps": [
		{
			"Type": "Text",
			"Label": {
				"en": "Are you married yet?"
			}
		}
	],
        ...
```

What do you think? @OlivierBourdin @rhwy

**Comment by andreasdieryck** [comment]
Following our conversation with @OlivierBourdin, we will settle on an expression such as follows:

```
"Type": "Node",
"Condition": "ppSingle == false"
"Id": "MarriedYet",
"Steps": [
		{
		    "Type": "Text",
		    "Label": {
			"en": "Are you married yet?"
		     }
		}
	],

```

That would be for a simple case, with one variable involved. In the cases when 2 variations are involved, it should look like this:

```
"Type": "Node",
"Condition": "ppSingle == false && ppAge == 41-64"
"Id": "MarriedYet",
"Steps": [
		{
		    "Type": "Text",
		    "Label": {
			"en": "Are you married yet?"
		     }
		}
	],

```

@OlivierBourdin is this correct?

**Comment by OlivierBourdin** [comment]
I just updated the example to ppCountry == 'France' instead of ppAge = xxxx, to make it clearer that this specific example uses a string variable.
We can have several level of implementations for expressions 
L0 : only one variable, which is a boolean
we would evaluate "Condition": "ppSingle == true" or "Condition": "ppSingle" to true if ppSingle exists and is true
L1: several variables, all booleans, with tokens "&&", "||",  "(" and ")"
like in "ppSingle == true && ( ppIsWomanizer || ppHasTime)"
L2: same as L1, but we can also use string variables
L3: we can evaluate a full expression, but need to discuss if we use C, C#, javascript or java syntax
It depends on how @rhwy and @Frederikos plan on parsing expressions

**Comment by Frederikos** [comment]
@OlivierBourdin 
1. C, C#, javascript or java syntax - syntax for expressions should be same for all c-type languages if we use base expression format.
2. As for evaluation - we can use additional parsing(replace using regular expressions or other method) to get all ppUserProperty variables and replace them by real values and after that use Expression engine like this https://github.com/mohitkgupta/expressionoasis to get expression boolean result.
3. As for user properties type - they all have string type now, not boolean. This expression is ok - ppSingle == true, but for this  ppIsWomanizer || ppHasTime we need to know for sure that property is boolean.

**Comment by rhwy** [comment]
I agree with @Frederikos on all the points,
we need to have a real expression, we won't re-invent the wheel and create a special parser for that, we'll use an existing engine that can do the job.

that means:
* the expression should be "syntax-compatible" with java/c#
* strings have to be strings like `some==\"hello\"` not `some==hello` or `some=='hello`
* implicit bool values (js like) should be avoided (ok: `some==true`, not ok: `some`)

also, as we don't know in advance, the named variables, I plan to create for the testing condition a var `user` (or context if you prefer) that will carry the values. 

basically we could simply understand an expression like:
`"user.Locale == \"fr-FR\" && ( user.AgeRange=\"18-39\" || user.Properties[\"ppSomeProperty\"] != null )`

this is a need, I can't evaluate/replace variables I don't know. once it's a property of a known variable (here `user`) I can work.


note: i know that writing `\"` is painful and minimises clarity, so, if we agree that a simple quote is used to delimited strings and that it will never used in another way, you wan write expressions with simple quotes instead of doubles and we'll do a search/replace(simple, double) before evaluating the expression.

note2: we don't need all these steps L0,...L3. as long as we'll use an expression engine, the problem won't be on the complexity of the expression.
